# Generated by Django 5.2.8 on 2025-11-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='score',
            name='game',
            field=models.CharField(choices=[('arkanoid', 'Arkanoid'), ('shoulder-bird', 'Shoulder-Bird')], max_length=50),
        ),
        migrations.AlterField(
            model_name='score',
            name='player_name',
            field=models.CharField(max_length=100),
        ),
    ]
